# Generated by Django 4.2.2 on 2023-06-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="photo_url",
            field=models.URLField(blank=True),
        ),
    ]
