# Generated by Django 4.2.2 on 2023-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_author_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo_url",
            field=models.URLField(),
        ),
    ]
